# Generated by Django 4.2.25 on 2025-10-16 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='issues.user'),
        ),
        migrations.AddField(
            model_name='issue',
            name='label',
            field=models.CharField(choices=[('bug', 'Bug'), ('enhancement', 'Enhancement'), ('documentation', 'Documentation'), ('feature', 'Feature')], default='bug', max_length=50),
        ),
    ]
