# Generated by Django 4.2.25 on 2025-10-21 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_assignee_issue_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_issues', to='issues.user'),
        ),
        migrations.CreateModel(
            name='PullReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20)),
                ('label', models.CharField(choices=[('bug', 'Bug'), ('development', 'Development'), ('ui', 'Ui'), ('documentation', 'Documentation'), ('feature', 'Feature')], default='bug', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pull', to='issues.user')),
                ('issue', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pull_request', to='issues.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pullreqs', to='issues.project')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_pul', to='issues.user')),
            ],
        ),
    ]
