# Generated by Django 4.2.25 on 2025-10-21 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_reviewer_pullreq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullreq',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pullreqs', to='issues.issue'),
        ),
    ]
