# Generated by Django 4.2.25 on 2025-10-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_pullreq_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullreq',
            name='label',
            field=models.CharField(choices=[('bug', 'Bug'), ('development', 'Development'), ('enhancement', 'Enhancement'), ('ui', 'Ui'), ('documentation', 'Documentation'), ('feature', 'Feature')], default='bug', max_length=50),
        ),
    ]
