# Generated by Django 4.2.25 on 2025-10-30 15:23

from django.db import migrations, models
import issues.models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_role_rolepermission_userrole_alter_issue_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.JSONField(default=issues.models.default_permissions),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
    ]
